### ISSUE TITLE
404 issue for Getting Started With Embeddings blog post

### ISSUE THREAD

**Issue by NamburiSrinath** [huggingface/blog#1194]
Hi,

For a reference in [this](https://huggingface.co/spaces/sentence-transformers/Sentence_Transformers_for_semantic_search) blog post, I am getting 404 error.

Redirected link where 404 issue is coming: [https://huggingface.co/spaces/sentence-transformers/Sentence_Transformers_for_semantic_search](https://huggingface.co/spaces/sentence-transformers/Sentence_Transformers_for_semantic_search)

Can you please update it?

Thanks

**Comment by pcuenca** [comment]
Hi @NamburiSrinath! The issue has been resolved, thanks a lot for reaching out!
