### ISSUE TITLE
Save Blog

### ISSUE THREAD

**Issue by alielfilali01** [huggingface/blog#1443]
Hello there, i'am opening this issue only because i wanted to contact to team taking charge of HF blog and suggest the Save Blog button ! that would be a great feature to add i believe ! Thank you for the great work HF Team

**Comment by pcuenca** [comment]
Hello @alielfilali01, and thanks a lot for your nice words! 🙌 

You can subscribe to the RSS feed using the following URL: https://hf.co/blog/feed.xml, would that work for you?

**Comment by alielfilali01** [comment]
No i meant a button like the one in medium etc where i can save the blogs i like the most or i want to get back to another time without much trouble remembering the name 😶 anyway just a suggestion that i believe would be great added feature to the blogs section of the website

**Comment by alielfilali01** [comment]
@julien-c exactly that's what i'am doing currently saving all the blogs i want into a bookmark titled 'HF-Blogs', just it would be cool to have it in the website :)
i will close this for now, thanks for responding @pcuenca & @julien-c
