### ISSUE TITLE
Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`:

### ISSUE THREAD

**Issue by farizalmustaqim** [huggingface/blog#1445]
ImportError   Traceback (most recent call last)

[<ipython-input-33-89b3691c8fc5>](https://localhost:8080/#) in <cell line: 3>()
      1 from transformers import Trainer, TrainingArguments
      2 ----> 3 training_args = TrainingArguments(
      4     output_dir="./EsperBERTo",
      5     overwrite_output_dir=True,

4 frames

[/usr/local/lib/python3.10/dist-packages/transformers/training_args.py](https://localhost:8080/#) in _setup_devices(self)
   1765         if not is_sagemaker_mp_enabled():
   1766             if not is_accelerate_available(min_version="0.20.1"):
-> 1767                 raise ImportError(
   1768                     "Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`"
   1769                 )

ImportError: Using the `Trainer` with `PyTorch` requires `accelerate>=0.20.1`: Please run `pip install transformers[torch]` or `pip install accelerate -U`

![image](https://github.com/huggingface/blog/assets/54091450/3a31fe72-f5bd-4480-88a0-f6235d17e237)

I've installed the packages according to the error message, but it still doesn't work.

**Comment by rajeshdavidbabu** [comment]
Check this fix here https://github.com/huggingface/transformers/issues/24147

**Comment by adityatodi** [comment]
This issue was raised post the fix mentioned in your link.

**Comment by farizalmustaqim** [comment]
thank you
