### ISSUE TITLE
Add syntax highlighting to code snippets

### ISSUE THREAD

**Issue by apolinario** [huggingface/blog#1561]
Even when the code specifies the syntax highlight language (https://github.com/huggingface/blog/blob/main/sdxl_jax.md?plain=1#L63), our code snippets still look like this: 

<img width="795" alt="image" src="https://github.com/huggingface/blog/assets/788417/03373478-51f4-4c8b-b3c2-7bbe016d9d00">

Would be cool to have beautiful colored syntax highlighting text

**Comment by osanseviero** [comment]
Does this also happen to you in incognito/other browsers? I've seen this in the past and ended up working when in incognito

**Comment by pcuenca** [comment]
Fixed in #1563
