### ISSUE TITLE
Llama for non engineers- URL points to wrong page

### ISSUE THREAD

**Issue by EmilyWitko** [huggingface/blog#1562]
<img width="847" alt="image" src="https://github.com/huggingface/blog/assets/2745998/36f8b742-f54f-4b51-9f9b-ce49566bf6e3">

it should be huggingface.co/spaces not https://huggingface.co/docs/hub/spaces

**Comment by julien-c** [comment]
care to open a PR @EmilyWitko? we can walk you through it! 🦾

**Comment by VioletteLepercq** [comment]
same issue reported here https://github.com/huggingface/blog/pull/1557
so this is WIP

**Comment by julien-c** [comment]
ok i think this can be closed then!
