### ISSUE TITLE
[FALCON 40B Demo Link Borken] Q Link for fix?

### ISSUE THREAD

**Issue by SoyGema** [huggingface/blog#1594]
### Context
Hello there! Thanks for the didactic [blog post](https://huggingface.co/blog/falcon) about Falcon! 🤓

### Link Broken
Found the [Demo Space](https://huggingface.co/blog/falcon#demo) Link Broken, as far as I´m understanding this link is maintained by RLHF team inside HF ? 
### Fix Question
I was going to submit a PR mimicking what happened in #1450 with 180b version 
but all I could found that is similar is [this](https://huggingface.co/spaces/HuggingFaceH4/falcon-chat) 
Would it be okísh if I submit a PR with the link described above to fix this ?
If not, happy if you point me in the right direction to submit a quick fix!
🙏Thanks🙏

**Comment by osanseviero** [comment]
This is now fixed after restarting the Space!

**Comment by SoyGema** [comment]
Thanks @osanseviero !
Closing it :)
