### ISSUE TITLE
Question about personal-copilot blog

### ISSUE THREAD

**Issue by garrettApproachableGeek** [huggingface/blog#1625]
Hey HF team,

Thanks for the blog, it has been awesome to follow along with

[personal-copilot.md](https://github.com/huggingface/blog/blob/cb6683e494beca3b04d2950ae99d3b35d6634fbf/personal-copilot.md)

I am at the point where I have a fine-tuned QLoRA model, but it isn't clear to me how to go from that fine-tuned model to a merged model like [smangrul/starcoder1B-v2-personal-copilot-merged](https://huggingface.co/smangrul/starcoder1B-v2-personal-copilot-merged) 

It seems like it is skipped over in this text from the blog `We used our QLoRA model, exported as a full-sized merged model that can be easily loaded in transformers.` maybe this is something that everyone else knows how to do, but as someone that doesn't know what they are doing I am stuck.

Thank you all!

**Comment by pcuenca** [comment]
Hi @garrettApproachableGeek, it's a great question and I'm sure others will have it too.

The following should work, using one of the LoRAs mentioned in the post:

```py
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel, PeftConfig

peft_model_id = "smangrul/peft-lora-starcoderplus-chat-asst-A100-40GB-colab"
config = PeftConfig.from_pretrained(peft_model_id)
model = AutoModelForCausalLM.from_pretrained(config.base_model_name_or_path)
model = PeftModel.from_pretrained(model, peft_model_id)
tokenizer = AutoTokenizer.from_pretrained(config.base_model_name_or_path)

merged_model = model.merge_and_unload()

merged_model.save_pretrained("/data/models/starcoder-merged", safe_serialization=True)
tokenizer.save_pretrained("/data/models/starcoder-merged")
```

You can also use `merged_model.push_to_hub` to upload the merged model to the hub so you can deploy it later.

**Comment by pcuenca** [comment]
cc @pacman100 @sayakpaul in case they want to add anything

**Comment by sayakpaul** [comment]
Thanks very much @pcuenca! Nothing to add from my end.

**Comment by pacman100** [comment]
@pcuenca explained it nicely and it should resolve the issue, nothing more to add.
