### ISSUE TITLE
Clarification: Fine-tuning a 4 Bit quantised model directly without LoRA Adapters

### ISSUE THREAD

**Issue by alexcpn** [huggingface/blog#1658]
As per the documentation  https://github.com/huggingface/blog/blob/main/4bit-transformers-bitsandbytes.md#can-we-train-4bit8bit-models it is not possible

```
Can we train 4bit/8bit models?
It is not possible to perform pure 4bit training on these models. However, you can train these models by leveraging parameter-efficient fine-tuning methods (PEFT) and train for example adapters on top of them. That is what is done in the paper and is officially supported by the PEFT library from Hugging Face.
```
However, with GPUs that support `bfloat16' (A100 GPU), I was able to do direct training without LoRA adapters and with just BitsandBytes config with `bf16` set to True. This is without any Instruction Training dataset generation directly on a raw generated text and the model seems to assimilate knowledge of the text on cursory evaluation. I have done this before also and found similar results.

See collab/git code - https://github.com/alexcpn/transformer_learn/blob/main/Mistral_7b_4bq_train.ipynb

Is this a feature that is not yet reflected in the documentation? 

Just to give a context on why I did not use LoRA. 

 I have found that with generated Instruction Tuning dataset QLoRA QLoRA-based training works great. ([see this Colab](https://colab.research.google.com/drive/1r7OmAZypaid2IVh-bNtl-olnDt45LdNP?usp=sharing)). But training on the raw data, (without generating the Instruction Tuning data set) without QLORA, and just Quantised models seems to be better. As part of that experimentation, I hit on this and would like to clarify.

**Comment by Neelectric** [comment]
Hey Alex, thank you for sharing your experience on this. 4bit model training without LoRA is exactly what I'm looking into at the moment too due to some constraints, and I'm eager to try out the method you describe the next chance I get. I was curious if you could share some details on the memory profile of this workaround? How much GPU VRAM does 4bit training take up compared to 4bit inference/full weight training in your experience? And does saving the model locally/to the hub work too? Thank you so much in advance :)

**Comment by alexcpn** [comment]
closed here https://github.com/huggingface/peft/issues/1342

**Comment by Neelectric** [comment]
Thank you kindly for your swift reply. I see now what is going on. In your script, we get the following for each layer (taking layer 0 as an example):
	Weight: model.layers.0.self_attn.q_proj.weight | Size: torch.Size([8388608, 1]) | Trainable: False
	Weight: model.layers.0.self_attn.k_proj.weight | Size: torch.Size([8388608, 1]) | Trainable: False
	Weight: model.layers.0.self_attn.v_proj.weight | Size: torch.Size([8388608, 1]) | Trainable: False
	Weight: model.layers.0.self_attn.o_proj.weight | Size: torch.Size([8388608, 1]) | Trainable: False
	Weight: model.layers.0.mlp.gate_proj.weight | Size: torch.Size([22544384, 1]) | Trainable: False
	Weight: model.layers.0.mlp.up_proj.weight | Size: torch.Size([22544384, 1]) | Trainable: False
	Weight: model.layers.0.mlp.down_proj.weight | Size: torch.Size([22544384, 1]) | Trainable: False
	Weight: model.layers.0.input_layernorm.weight | Size: torch.Size([4096]) | Trainable: True
	Weight: model.layers.0.post_attention_layernorm.weight | Size: torch.Size([4096]) | Trainable: True

So in total, the layernorms, the embeddings and the LM head are trainable. But setting requires_grad to true for self_attn or MLP parameters when in 4bit seems like it is not possible. Do you know any workaround there? Can we train self_attn or MLP modules in 4bit too without LoRA?

**Comment by alexcpn** [comment]
> Can we train self_attn or MLP modules in 4bit too without LoRA?

it should be possible to set `requires_grad` as True for the layer we need. But setting it for self attention blocks would mean huge amount of resources right. Maybe you are thinking for few attention layers to also enable. It should be possible,something like this ? https://github.com/alexcpn/transformer_learn/blob/main/decoders/gpt2_train_model.py#L103-L107
