### ISSUE TITLE
need help with joining the organization - "Blog explorers"

### ISSUE THREAD

**Issue by Raghavan1988** [huggingface/blog#1723]
https://github.com/huggingface/blog/pull/1604
Based on this PR, i tried to join the organization https://huggingface.co/blog-explorers  to contribute to the community blog which states, joining would be approved shortly.
However, i have not been approved. Could anyone help me with the process? or show me pointers on how to write community blog.

**Comment by osanseviero** [comment]
It seems you've been added already
