### ISSUE TITLE
Are images cached?

### ISSUE THREAD

**Issue by clefourrier** [huggingface/blog#1780]
This [link](https://huggingface.co/blog/assets/leaderboards-on-the-hub/thumbnail.png) should redirect to [this image](https://github.com/huggingface/blog/blob/main/assets/leaderboards-on-the-hub/thumbnail.png) but it redirects to the v0 version (not even the v1 updated yesterday).

**Comment by clefourrier** [comment]
(btw @osanseviero please tell me if I should ping someone else)

**Comment by pcuenca** [comment]
Yes, the [images are cached](https://github.com/huggingface/blog/pull/1641#issuecomment-1804353433). What we've done in the past is change the filename. There may be a way to invalidate the caches, but I don't know what it is. Perhaps it just resolves if we wait?

**Comment by julien-c** [comment]
yes they're cached 24 hours. Change the filename if you want to have it rotate earlier than 24 hours! is the official workaround

**Comment by clefourrier** [comment]
24h is super fine! Thanks a lot, that works for me :)

**Comment by julien-c** [comment]
(i _think_ it's 24hours? cc @rtrompier @XciD)

**Comment by rtrompier** [comment]
I confirm. Path `/blog/assets/*` is cached for 24h.

**Comment by clefourrier** [comment]
All good now! Thanks to you all!
