### ISSUE TITLE
Codelab issue Fine-Tune Whisper For Multilingual ASR with 🤗 Transformers

### ISSUE THREAD

**Issue by K1100** [huggingface/blog#1794]
A quick run on your codelab, and got this error on evaludation:

=================

Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.
.'` or make sure all input audio is of the same language."
   1168                 )

ValueError: Multiple languages detected when trying to predict the most likely target language for transcription. It is currently not supported to transcribe to different languages in a single batch. Please make sure to either force a single language by passing `language='...'` or make sure all input audio is of the same language.

**Comment by K1100** [comment]
Found solution to enforce single language as below in the model config:

MODEL_NAME = "openai/whisper-medium"
LANGUAGE = "Vietnamese"
TASK = "transcribe"
MAX_LENGTH = 224



model.config.forced_decoder_ids = processor.tokenizer.get_decoder_prompt_ids(
    language=LANGUAGE, task=TASK
)
model.config.suppress_tokens = []
model.generation_config.forced_decoder_ids = processor.tokenizer.get_decoder_prompt_ids(
    language=LANGUAGE, task=TASK
)
model.generation_config.suppress_tokens = []

**Comment by RitchieP** [comment]
Hi, I tried implementing your solution but I'm still stuck. I've set my transformer to have logging log verbosely, and this is what I see.
![image](https://github.com/huggingface/blog/assets/26197115/4978e51f-776f-48e2-9c87-9a8272532791)
It just stops and shows nothing when running evaluation. Any idea on why this is?
