### ISSUE TITLE
Please update the blog to fix: "Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription"

### ISSUE THREAD

**Issue by d2a-raudenaerde** [huggingface/blog#1948]
I'm trying to trying to do the "https://huggingface.co/blog/fine-tune-whisper" so I setup an gpu supporterd jupyter. 

However, after the first evaluation print (1000 steps), I get this error:

`Due to a bug fix in https://github.com/huggingface/transformers/pull/28687 transcription using a multilingual Whisper will default to language detection followed by transcription instead of translation to English.This might be a breaking change for your use case. If you want to instead always translate your audio to English, make sure to pass `language='en'`.`

I'm sure there is a workaround, but could you please update the blog with these new settings?

**Comment by d2a-raudenaerde** [comment]
Ok i was too fast maybe it has a fix in #1944?

**Comment by pcuenca** [comment]
Yes, that PR was just merged :) Can you give a try and see if it works for you?

**Comment by d2a-raudenaerde** [comment]
![image](https://github.com/huggingface/blog/assets/5213150/20f0d6b4-279c-43c6-96eb-996b8da9ca2d)

**Comment by d2a-raudenaerde** [comment]
I only copied the model config part (searched for 'hindi' in the source') 
```
model.generation_config.language = "hindi",
model.generation_config.task = "transcribe",
model.generation_config.forced_decoder_ids = None
```
Maybe I forgot it somewhere.. Will check!

**Comment by d2a-raudenaerde** [comment]
Ah the error shows it is a tuple `('hindi,)` and the list contains `'hindi'` as a regular string.

**Comment by pcuenca** [comment]
Yes, I think those trailing commas in [your code snippet](https://github.com/huggingface/blog/issues/1948#issuecomment-2029514205) should not be there. This is how the blog shows up for me:

<img width="535" alt="Screenshot 2024-04-01 at 12 37 01" src="https://github.com/huggingface/blog/assets/1177582/29953383-bc80-4e05-8973-daca057aa172">

**Comment by d2a-raudenaerde** [comment]
Oh I see it is a copy paste error :S

**Comment by d2a-raudenaerde** [comment]
Ok now it goes further. I reduced the evaluation steps to see error sooner. However, the output seems empty?
![image](https://github.com/huggingface/blog/assets/5213150/4bb4f6b8-847c-46c1-881d-8adffef0dd09)

**Comment by d2a-raudenaerde** [comment]
Ok I see this is to be expected and the second bar is the 'evaluation' process. Seems to work as I now have a first evaluation after 100 steps. (not recommended as evalutation takes about 10 minutes on my system)
