### ISSUE TITLE
[bug] zh/ blog titles displaying in English & missing translation links

### ISSUE THREAD

**Issue by chenglu** [huggingface/blog#1965]
I've noticed a problem on the Hugging Face Chinese blog page (https://hf.co/blog/zh) where the titles of the articles, expected to be in Chinese, are instead shown in English. These titles are correctly displayed in Chinese on the blog detail pages.

Also, links to Chinese translations on English blog pages and to English original on Chinese blog pages are now missing.

Could we please investigate this issue and implement a fix? 

Thanks!

Screenshot:

<img width="962" alt="image" src="https://github.com/huggingface/blog/assets/2258420/2452af2d-85b4-466f-a8da-b5bd9c457093">

**Comment by julien-c** [comment]
or possibly @krampstudio recent change.

@chenglu do you know when this started happening?

**Comment by krampstudio** [comment]
> or possibly @krampstudio recent change

yes, my bad. Taking the title from the db (along with the number of upvotes) instead of the yaml.

**Comment by chenglu** [comment]
> or possibly @krampstudio recent change.
> 
> @chenglu do you know when this started happening, by any chance?

Thank you for taking the time to investigate this issue. From what I remember, this started happening just in the past 1 or 2 weeks. 

The newly added upvote feature is great! But please take some time to see if we could "revert" some previous features that shown the Chinese/ English links, as well as the titles on the Chinese Language blog page, thanks!

**Comment by krampstudio** [comment]
@chenglu everything should be fixed now: titles in thumbnails and the link to other languages versions.

**Comment by xianbaoqian** [comment]
Yeah it's now. Thanks for the prompt fix!
