### ISSUE TITLE
Add Llama3! 

### ISSUE THREAD

**Issue by arthrod** [huggingface/blog#2018]
Please :)

**Comment by pcuenca** [comment]
What do you mean @arthrod? https://huggingface.co/blog/llama3

**Comment by arthrod** [comment]
For the inference pro users!

**Comment by pcuenca** [comment]
Ah! There are some technical constraints, we need to be GPU-richer :) We'll see what we can do.

**Comment by osanseviero** [comment]
It's now up there!
