### ISSUE TITLE
[Question] Sentence Transformers V3

### ISSUE THREAD

**Issue by austinmw** [huggingface/blog#2112]
Hi, hard negative mining was mentioned in the blog post. Does the sentence-transformers library currently have any utility methods to generate hard negatives from a dataset and model?

**Comment by osanseviero** [comment]
Hi there! I would recommend opening an issue in `sentence-transformers` or the forum for those questions.

cc @tomaarsen in any case

**Comment by tomaarsen** [comment]
(For those who stumble upon this: https://github.com/UKPLab/sentence-transformers/issues/2697)
