### ISSUE TITLE
Permission to Use Image

### ISSUE THREAD

**Issue by zoyahammad** [huggingface/blog#2203]
I am a high school student researching on different text-to-image models. I would like to use one of your diagrams (Stable Diffusion Architecture) from here: https://github.com/huggingface/blog/blob/main/stable_diffusion.md
 
However, my potential publisher (JEI) requires an official permission from the creators/owners beforehand. Would you be able to give such a permission? If not, could you please let me know who's the best person to contact for this? I will be looking forward to hearing from you. Thank you.
 

![stable_diffusion (1)](https://github.com/huggingface/blog/assets/134557773/3ad78496-ae12-4b83-9049-b3ebba2e2f3d)

**Comment by julien-c** [comment]
cc @patil-suraj maybe

**Comment by pcuenca** [comment]
I think the diagram may have been created by @natolambert

**Comment by natolambert** [comment]
Sounds good to me, with credit if you can, but no big deal!

**Comment by julien-c** [comment]
thx!
