### ISSUE TITLE
Llama3.1 70B full fine-tuning memory usage

### ISSUE THREAD

**Issue by jack242860823** [huggingface/blog#2245]
I saw this chart from (https://github.com/huggingface/blog/blob/main/llama31.md)
<img width="870" alt="截圖 2024-07-25 下午6 24 11" src="https://github.com/user-attachments/assets/089cf6f1-037b-4fea-8b3b-f04799714968">

In this chart, it is mentioned that training Llama 3.1 requires 300 GB of memory for full parameter fine-tuning of the 70B model. However, if we assume FP16 training, the expected memory usage should be around eight times the model size, similar to the results observed with the 8B or 405B models. This implies that the memory requirement for the 70B model should be around 500 GB or more.

Is my understanding incorrect? Or are there any specific techniques being used to perform full parameter fine-tuning?

Thank you!

**Comment by philschmid** [comment]
Thank you @jack242860823. You are correct ~300GB is roughly what it takes to load the model in fp16. ~519GB is what i got using https://huggingface.co/docs/accelerate/en/usage_guides/model_size_estimator for fine-tuning. Will update.

**Comment by aakash0017** [comment]
This is completely wrong. please refer to official repo for exact memory utilization: https://github.com/meta-llama/llama-recipes/blob/main/recipes/quickstart/finetuning/multigpu_finetuning.md
