### ISSUE TITLE
A failed experiment: Infini-Attention, and why we should keep trying?

### ISSUE THREAD

**Issue by efeecllk** [huggingface/blog#2300]
Photos are not visible in this article
<img width="900" alt="Screenshot 2024-08-14 at 19 24 00" src="https://github.com/user-attachments/assets/8a36f524-38ac-455b-9ab1-911f918d3b0a">

**Comment by pcuenca** [comment]
Fixed in #2301 and #2302. Thank you, @efeecllk!

**Comment by efeecllk** [comment]
You're welcome
