### ISSUE TITLE
Silly question on tokenizers

### ISSUE THREAD

**Issue by Pradhy729** [huggingface/blog#24]
I was coding along with the how to train language model from scratch blog & notebook and I had a question. 

Why do we first create, train and save a tokenizer from tokenizers.ByteLevelBPETokenizer() and then use it to create another ByteLevelBPETokenizer from tokenizers.implementations? Are these the same? If not, what is the difference? Could we have just used the same tokenizer object we initially trained to then to postprocessing and truncation etc.?

It may help to explain this in the blog if others are confused like I was.

**Comment by Pradhy729** [comment]
Oops nevermind - I think I figured it out. The second part is just an example of how we could use the pretrained tokenizer in the Tokenizer library.

**Comment by julien-c** [comment]
Yes that's correct. You should be able to just use it from `transformers` too.
