### ISSUE TITLE
Hi, I am trying to join the blog-explorers, but the request has not been approved for quite some time

### ISSUE THREAD

**Issue by royswastik** [huggingface/blog#2445]
I tried requesting to join the organization https://huggingface.co/blog-explorers to contribute to the community blog which states, joining would be approved shortly.

However, i have not been approved. Could anyone help me with the process? or show me pointers on how to get approval to contribute blogs.

https://huggingface.co/blog-explorershttps://huggingface.co/blog-explorers

**Comment by julien-c** [comment]
Hi @royswastik – just approved your request.

Write some good stuff!
