### ISSUE TITLE
Missing link to datasets in SmolVLM blog

### ISSUE THREAD

**Issue by sergiopaniego** [huggingface/blog#2495]
In [SmolVLM - small yet mighty Vision Language Model](https://huggingface.co/blog/smolvlm) blog, it seems like there is a missing link:

```
 The full list of datasets we used can be consulted here (link to the datasets)
```

I'd fix it but I'm not sure about the correct pointer 😅 

@pcuenca @merveenoyan

**Comment by pcuenca** [comment]
Thanks a lot @sergiopaniego! This was fixed by @andimarafioti at more or less the same time you reported it :)
