### ISSUE TITLE
Incorrect Memory Calculations in Blog Post

### ISSUE THREAD

**Issue by austinmw** [huggingface/blog#2561]
[Hugging Face Blog: Visualize and Understand GPU Memory](https://huggingface.co/blog/train_memory)

There are discrepancies in the memory usage calculations presented in the blog. Below are the identified issues with detailed corrections.

Steps with Errors:
	1.	Step 1: Model Creation
	•	Blog Claim: 4 GB
	•	Correct Calculation:
	•	Parameters: 10,000 x 50,000 + 50,000 = 500,050,000
	•	Memory: 500,050,000 x 4 bytes = 2 GB
	•	Issue: Memory usage is overestimated as 4 GB instead of 2 GB.
	2.	Step 3: Forward Pass (1st Loop)
	•	Blog Claim: 2 GB
	•	Correct Calculation:
	•	Output: 5,000 x 50,000 = 250,000,000
	•	Memory: 250,000,000 x 4 bytes = 1 GB
	•	Issue: Memory usage is overestimated as 2 GB instead of 1 GB.
	3.	Step 5: Forward Pass (2nd Loop)
	•	Blog Claim: 2 GB
	•	Correct Calculation:
	•	Output: 5,000 x 50,000 = 250,000,000
	•	Memory: 250,000,000 x 4 bytes = 1 GB
	•	Issue: Memory usage is overestimated as 2 GB instead of 1 GB.
	4.	Step 9: Forward Pass (3rd Loop)
	•	Blog Claim: 2 GB
	•	Correct Calculation:
	•	Output: 5,000 x 50,000 = 250,000,000
	•	Memory: 250,000,000 x 4 bytes = 1 GB
	•	Issue: Memory usage is overestimated as 2 GB instead of 1 GB.

Summary of Issues:
	•	Step 1: Memory for model creation is listed as 4 GB but should be 2 GB.
	•	Steps 3, 5, 9: Forward pass memory is listed as 2 GB per loop but should be 1 GB per loop.

**Comment by pcuenca** [comment]
Related: #2563 cc @qgallouedec @vinay-hebb
