### ISSUE TITLE
encoder-decoder (bert2bert) model for summarization task doesn't work in v4.18

### ISSUE THREAD

**Issue by AbuUbaida** [huggingface/blog#292]
This [notebook](https://colab.research.google.com/github/patrickvonplaten/notebooks/blob/master/Leveraging_Pre_trained_Checkpoints_for_Encoder_Decoder_Models.ipynb#scrollTo=3FO5ESocXvlK) ([github link](https://github.com/huggingface/blog/blob/main/warm-starting-encoder-decoder.md#warm-starting-encoder-decoder-models-with-transformers-practice)) is a great roadway to summarization task. However, the **BERT2BERT** model demonstrated by @patrickvonplaten doesn't work properly in **transformers v4.18**. What the model always generates is just a summary _(vector of tokens)_ that contains only special tokens like `[CLS]`, and `[SEP]` regardless of the input. In my case, the output was something like this:
`[CLS] [CLS] [CLS] [CLS] [CLS] ............................ [SEP]`

@patrickvonplaten  or anybody could say please what the necessary adjustments might be needed in that existing [blog](https://huggingface.co/blog/warm-starting-encoder-decoder#data-preprocessing)?

**Comment by patrickvonplaten** [comment]
Hey @AbuUbaida,

Thanks for opening this issue. Currently I sadly don't have much time to fix this, but I'd be happy to work on it together if you want. 

If you'd like, you could copy the google colab, then pin Transfomers to the new 4.18 version, and then we see together how to make it work?

**Comment by AbuUbaida** [comment]
Thanks, @patrickvonplaten for getting back to me. I have shared a [copy](https://colab.research.google.com/drive/1kH5lXGeQVPUEPqzuY5l3mw-fI6OXE7aE?usp=sharing) of the [notebook](https://colab.research.google.com/drive/1Ekd5pUeCX7VOrMx94_czTkwNtLN32Uyu?usp=sharing) with you pinned with **transformers** and **datasets** at their latest releases **4.18.0** and **2.1.0** respectively.
You could give directions on what next if you want. Thanks!

**Comment by AbuUbaida** [comment]
Alhamdulillah! It’s now working for me surprisingly; just run the cells of the colab notebook with my custom model what I did earlier also, but this time explicitly mentioned `transformers==4.18.0` and `datasets==2.1.0` in the code. Though it doesn’t make sense to me since the latest version was being installed previously by default without mentioning explicitly.

**Comment by patrickvonplaten** [comment]
Interesting...I don't seem to have access to the copy of your notebook :-)

**Comment by AbuUbaida** [comment]
@patrickvonplaten  sorry for being late. Actually, I removed the file as all was going right. But, maybe last time, I also needed to restart the runtime after checking versions several times. Thanks for the lucky instruction: :-)
> then pin Transformers to the new 4.18 version
