### ISSUE TITLE
List a Space as a blog post on hf.co/blog

### ISSUE THREAD

**Issue by jeffboudier** [huggingface/blog#343]
*for discussion*

Spaces enable interactive blog experiences, like https://huggingface.co/spaces/loubnabnl/code-generation-models

As an interactive blog post author, I want to add an entry in the blog [blog.yaml](https://github.com/huggingface/blog/blob/main/_blog.yml) to list the space as a blog post to show up on hf.co/blog

**Comment by julien-c** [comment]
and you can!  just use `external: full_url` in https://github.com/huggingface/blog/blob/main/_blog.yml

**Comment by Pierrci** [comment]
Can we close this? :)
