### ISSUE TITLE
Multiple Issues while running

### ISSUE THREAD

**Issue by aditya-malte** [huggingface/blog#4]
Hi,
I found that there were multiple issues such as BPE tokenizers not being found,
Problems loading the tokenizer among others.
I'd suggest redoing the blog code to work with the current deployment and make the same publicly available.
Thanks

**Comment by julien-c** [comment]
Hi, your import issue would probably be fixed by https://github.com/huggingface/tokenizers/issues/133#issuecomment-586720001

**Comment by aditya-malte** [comment]
Thanks for the quick reply.
Actually it seems that I’m  facing some compatibility issue related to using the newer tokenizer library with transformers.
Among other issues, I’m facing a problem where the tokenizer so saved, is not being accepted by the run_language_model code(in examples folder).
Could you perhaps share the complete code for implementing the LM training(from scratch) shown in the blog, that way we can identify what changes must be made.
Meanwhile I’m working on a Colab example to aid others and would raise a PR when done.
Thanks again

**Comment by jbmaxwell** [comment]
Yes, I was super excited to see this post, but I'm a bit stumped getting it to run with my data. I think the blog post makes a big leap from the custom EsperantoDataset to giving the parameters for run_language_modeling.py. Seeing the modified training script would be great.

**Comment by aditya-malte** [comment]
@jbmaxwell, Agreed.
Don’t worry, I’ve got a Colab notebook working now(although it is specific to my task)
Will share soon.
Thanks

**Comment by jbmaxwell** [comment]
@aditya-malte No problem about it being specific to your task. I can separate out your specifics. Thanks, and looking forward to seeing what you've done!

**Comment by ohmeow** [comment]
Yah I'm a big confused with the tutorial as well ... how do we use the `run_language_modeling.py` script so that it uses the custom `Dataset`?

**Comment by ddofer** [comment]
> @jbmaxwell, Agreed.
> Don’t worry, I’ve got a Colab notebook working now(although it is specific to my task)
> Will share soon.
> Thanks

AWesome - I came in here trying to raise the same issue, and am also stuck in colab. Can you share with me as well please? tx!

**Comment by aditya-malte** [comment]
@jbmaxwell @ddofer 
Check this github gist.
A small example I have created
https://gist.github.com/aditya-malte/2d4f896f471be9c38eb4d723a710768b#file-smallberta_pretraining-ipynb
