### ISSUE TITLE
How to get the number of parameters and how to load the model after have Fine-tuned the model (and saved it)!

### ISSUE THREAD

**Issue by dgrnd4** [huggingface/blog#411]
Hi there, I followed the [tutorial on Fine-Tune ViT for Image classification](https://huggingface.co/blog/fine-tune-vit) and I was wondering how can I get the number of parameters of the model? which file in the files saved by the ones saved by the function shall I use to load the model?
This is [my projects](https://colab.research.google.com/drive/1Maye5rC2Fe6MqdKX9C5KxuYfrisUBkhX#scrollTo=DOkb3L-A-pM-) if you want to read it: I'm trying to fine-tune the model on "Stanford dog dataset"!

**Comment by osanseviero** [comment]
cc @nateraw

**Comment by nateraw** [comment]
I think this question would be better for the [forums](https://discuss.huggingface.co/). But to answer your questions

1. How to get num of parameters
I found this on the [pytorch forums](https://discuss.pytorch.org/t/how-do-i-check-the-number-of-parameters-of-a-model/4325/9).

2. Which file in the saved files shall you use to load the model
You load it by reference to the directory

```python
model = ViTForImageClassification.from_pretrained('path/to/save/dir/')
```

its loading `pytorch_model.bin` under the hood.

**Comment by dgrnd4** [comment]
many thanks, I solved both problem with:

```
metrics = trainer.evaluate(prepared_ds['validation'])
trainer.log_metrics("eval", metrics)
trainer.save_metrics("eval", metrics)
```
and 
```
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

model_parameters= count_parameters
model_parameters
```
