### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by timokau** [huggingface/blog#42]
Hi!

I just discovered this blog and would like to follow it. I usually do that with a rss reader, but I couldn't find any feed on the website. Am I missing it or is it just not there?

**Comment by Pierrci** [comment]
@timokau thanks to @muellerzr and @julien-c, we now have an RSS feed that is available when you're visiting [hf.co/blog](https://hf.co/blog) (and accessible directly at [hf.co/blog/feed.xml](https://hf.co/blog/feed.xml))

Please do report here if you encounter any problem w/ it - but for now, I'm closing this! 🍾

**Comment by timokau** [comment]
Thanks! The feed does not contain any text for the articles, I'm not sure if that is on purpose. Either way my use case is mostly about informing me when a new article is published, so that works for me.

**Comment by adaszko** [comment]
Hi!  I’m actually fine with missing text from the articles (just want to notice when a new article is published) but it seems the entries are missing the `<link>` element and thus “opening” the article doesn’t take me anywhere.  A sample entry:

```
  <item>
   <title>Large-scale Near-deduplication Behind BigCode</title>
   <pubDate>Tue, 16 May 2023 00:00:00 GMT</pubDate>
   <guid isPermaLink="true">https://huggingface.co/blog/dedup</guid>
  </item>
```

Here’s an entry from another, working feed:
```
<item>
<title>PRFs, PRPs and other fantastic things</title>
<link>https://blog.cryptographyengineering.com/2023/05/08/prfs-prps-and-other-fantastic-things/</link>
<comments>https://blog.cryptographyengineering.com/2023/05/08/prfs-prps-and-other-fantastic-things/#comments</comments>
[…]		
<guid isPermaLink="false">http://blog.cryptographyengineering.com/?p=5057</guid>
[...]
</item>
```

**Comment by adaszko** [comment]
> The link is in `guid`, and the RSS feed is validated: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhuggingface.co%2Fblog%2Ffeed.xml
> 
> Which client are you using?

Oh, interesting.  I’m using https://github.com/nkanaev/yarr

**Comment by julien-c** [comment]
thanks for reporting @adaszko and I'll give `yarr` a try now:)

**Comment by jasonbrancazio** [comment]
I'm having the same issue as @adaszko using the admittedly ancient FeedR RSS reader for Android
https://play.google.com/store/apps/details?id=com.feedr&hl=en_US&gl=US

It would be great if the feed XML was updated to at least provide the first paragraph of a blog post, and while doing so, also updated to use <link> instead of or in addition to <guid>.

**Comment by jkozak** [comment]
An RSS feed for papers would be nice, too.

**Comment by julien-c** [comment]
cc @AK391 could be a good idea! RSS feed for hf.co/papers

**Comment by DarkReaperBoy** [comment]
add support for per acc model/dataset release, like:
https://huggingface.co/Undi95/feed.xml

**Comment by Laurent2916** [comment]
an RSS feed for community blog posts would also be cool:
https://huggingface.co/blog/community

**Comment by mamarmite** [comment]
I would like a /posts/feed.xml too if I may <3
Still love the rss discoverability way to follow content.

**Comment by steveepreston** [comment]
++  RSS/Atom for Organizations Activities
