### ISSUE TITLE
How to convert a save ViT model into keras (.h5) or tensorFlowLight (tflite)

### ISSUE THREAD

**Issue by dgrnd4** [huggingface/blog#428]
Hi, I am trying to save my ViT model into a keras model (.h5) or a tflite model.
Is it possible? Can you please help me with it?

Many thanks!

**Comment by dgrnd4** [comment]
@nateraw @mariosasko

**Comment by nateraw** [comment]
I believe [this section](https://huggingface.co/docs/transformers/quicktour#save-a-model) of the docs may be helpful for you. Basically, you can save the model as pytorch, load it as Tensorflow, and then save it, which will give you an h5 file.

First, I'll load a pretrained model from the hub and save it to a new directory called `./my_model/`. 

```python
from transformers import AutoModelForImageClassification

model = AutoModelForImageClassification.from_pretrained('google/vit-base-patch16-224')
model.save_pretrained("my_model")
```

Then I'll load that pytorch model in to the TF version and save that (this time to a different dir called `./my_model_tf`). 

```python
from transformers import TFAutoModelForImageClassification

tf_model = TFAutoModelForImageClassification.from_pretrained("my_model", from_pt=True)
tf_model.save_pretrained("my_model_tf")
```

The resulting directory looks like this:

```
my_model_tf
├── config.json
└── tf_model.h5
```

**Comment by osanseviero** [comment]
Marking as closed as this is now solved :)

**Comment by nateraw** [comment]
@dgrnd4 I don't think this problem is an issue with the blog post, its related to your specific use case. So, it would be better if you posted your questions on the [forums](https://discuss.huggingface.co/). Let's leave this issue closed.
