### ISSUE TITLE
Training BERT model on the Hebrew Bible Transliteration corpus.

### ISSUE THREAD

**Issue by mstekel** [huggingface/blog#43]
Hi guys,

I tried following [this article](https://huggingface.co/blog/how-to-train) in order to train a BERT model from scratch on a corpus of the Hebrew Bible transliteration(for example, see the right column of the table on [this page](https://www.sacred-texts.com/bib/tan/gen001.htm#001)). I used the ByteLevelBPETokenizer. After training the model with the same configuration as you used for EsperBERTo (1 epoch etc.), I tried performing the "fill-mask" task on an arbitrary sentence from the corpus. Unfortunately the completions I got were weird - single characters, mainly the apostrophe and the hyphen(that are indeed widely used by the transliteration not as separate words but rather as signs for specific Hebrew consonants). Can you point out what I did wrong or alternatively what I can do to prevent this behavior?

P.S. running the same process on the original(not transliterated) Hebrew text of the Bible, despite the morphological complexity of Hebrew(written without vowels and thus every word might have many valid reading options depending on the context), has yielded much better results. The masks have been filled by valid Hebrew words, even though not necessarily matching the semantic context.

Here is [my notebook](https://colab.research.google.com/drive/1GPY6t5R3mXV6R-u0ftg8VsAiFvQ6KznF?usp=sharing).

Here is the disappointing screenshot:
![image](https://user-images.githubusercontent.com/1852087/88190264-bda77e80-cc42-11ea-805b-ff1431ee2884.png)

Thank you in advance,
Moshe.

**Comment by julien-c** [comment]
Hi Moshe,

I would suggest posting on https://discuss.huggingface.co which would be better suited to your question

**Comment by mstekel** [comment]
OK, I will.

Thanks,
Moshe.

‫בתאריך יום ה׳, 23 ביולי 2020 ב-10:41 מאת ‪Julien Chaumond‬‏ <‪
notifications@github.com‬‏>:‬
