### ISSUE TITLE
Building Training Dataset with multiple text files

### ISSUE THREAD

**Issue by jwaring-dfci** [huggingface/blog#44]
Hello, I am trying to follow the tutorial on how to train a language model from scratch found here: https://github.com/huggingface/blog/blob/master/notebooks/01_how_to_train.ipynb. However, I get stuck at building the training dataset, because I have multiple text files, whereas the example states "Here, as we only have one text file, we don't even need to customize our Dataset. We'll just use the LineByLineDataset out-of-the-box." 

How do I go about "customizing my Dataset" since I have multiple text files to use for the trainer in the following steps?

**Comment by julien-c** [comment]
I would advise to look into the `huggingface/nlp` library (brand new doc: https://huggingface.co/nlp/) – there's a generic `text` dataset – or to roll out your own Dataset

You can also try posting to discuss.huggingface.co
