### ISSUE TITLE
Adding audio samples(non supervised) to XLSR-53 model

### ISSUE THREAD

**Issue by arikhalperin** [huggingface/blog#471]
I have already used XLSR-53 successfully, fine-tuning it according : https://huggingface.co/blog/fine-tune-xlsr-wav2vec2

However I have a lot of unlabeled data. I understand that building a Wav2Vec model from scratch does not make sense, so I want to train a model
With my audio but use XLSR-53 as a base - but I could not find an explanation how to do it.

**Comment by sanchit-gandhi** [comment]
Hey @arikhalperin! Feel free to post in the forum: https://discuss.huggingface.co
You'll get more visibility on your question there and are more likely to get an answer!

Note that we can **only** use unlabelled data for pre-training. If you want pointers for pre-training Wav2Vec2/XLS-R, you can checkout the README here: https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-pretraining#speech-recognition-pre-training

So you could try pre-training according to this script initialising your weights with XLSR-53, then fine-tune according to the blog post.
