### ISSUE TITLE
Add ReviewNB to blog PRs

### ISSUE THREAD

**Issue by osanseviero** [huggingface/blog#479]
Some blog posts have accompanying notebooks, so ReviewNB would be very helpful. @NimaBoscarino or @simoninithomas, given you did this for the Deep RL Class, would you be up for adding it here as well?

**Comment by simoninithomas** [comment]
I didn't installed it it was @NimaBoscarino right? If you have the ReviewNb account credentials Nima I can do it?

**Comment by NimaBoscarino** [comment]
Yup, it was me! Anyone with write-access to a repo can log in on https://www.reviewnb.com and set it up. I'll do it right now :)

**Comment by NimaBoscarino** [comment]
Oh nope, actually I think it looks like I need admin access to a repo to be able to add it to ReviewNB, so someone else will have to do it. But @simoninithomas you should just be able to log in on ReviewNB and then it'll pull Hugging Face repos for you to choose from.

**Comment by osanseviero** [comment]
I also don't have admin access to this repo. Maybe @julien-c ? :smile:

**Comment by julien-c** [comment]
made you an admin to the repo!

**Comment by osanseviero** [comment]
Ok added! Thanks @NimaBoscarino for the pointer and @julien-c for giving me the power :magic_wand:
