### ISSUE TITLE
Can't access CompVis/stable-diffusion-v1-4 model

### ISSUE THREAD

**Issue by davidkh1** [huggingface/blog#486]
The pretrained model [`CompVis/stable-diffusion-v1-4`](https://huggingface.co/CompVis/stable-diffusion-v1-4) mentioned in the [blog](https://huggingface.co/blog/stable_diffusion) is not visible for me. [Its card](https://huggingface.co/CompVis/stable-diffusion-v1-4) returns 404 error code so can't sign its license.

More info: I'm logged in. My HuggingFace profile was created today.

Could you please check the issue.

**Comment by osanseviero** [comment]
This will be public in the next couple of minutes/hours :)

**Comment by davidkh1** [comment]
Works like a charm! Thanks.
