### ISSUE TITLE
Typo? On Decision Transformers

### ISSUE THREAD

**Issue by ironbar** [huggingface/blog#520]
https://github.com/huggingface/blog/blob/main/decision-transformers.md#evaluating-the-model

It says the following:

> We also need a target return for the model. This is the power of **Offline Reinforcement Learning**: we can use the target return to control the performance of the policy.

I believe the intention was to write the following:

> We also need a target return for the model. This is the power of **Decision Transformers**: we can use the target return to control the performance of the policy.

I believe this is a property of Decision Transformers, which is a subfield of Offline Reinforcement Learning. Not all Offline Reinforcement Learning methods share that property.

Thanks for the great course!

@simoninithomas @edbeeching

**Comment by simoninithomas** [comment]
Hey there 👋 , Thanks for the feedback, I'm just checking with the team how to reformulate this part. I'll keep you updated 🤗

**Comment by simoninithomas** [comment]
Updated here: https://github.com/huggingface/blog/pull/527

Thanks again for your feedback 🤗 I'm closing the issue here.
