### ISSUE TITLE
[proposal] drop assets ID

### ISSUE THREAD

**Issue by stas00** [huggingface/blog#530]
As disscused here https://github.com/huggingface/blog/pull/507#discussion_r974616495 and multiple times before the asset prefix ID (https://github.com/huggingface/blog/tree/main/assets) is not being used anywhere and it very often interferes with blog post PRs when multiple new PRs are opened, each using the **same** next id and a race condition ensues - the first to merge wins, the other open PRs now have to rename the assets folder and move files to the next id, and again a race condition occurs.

I propose to remove the id altogether and solve the race condition.

~Ideally we can then rewrite all the existing blog posts to remove the id as well to avoid confusion for future authors which may try to copy the old setup.~ (not good for direct links to previous assets)

Thank you!

**Comment by julien-c** [comment]
> Ideally we can then rewrite all the existing blog posts to remove the id as well to avoid confusion for future authors which may try to copy the old setup.

As discussed before (can't find the thread right now...), we shouldn't rename the existing folders because it would break the existing assets URLs linked from the Internet

So this leaves us with the options of 1/ ommitting the id going forward, or 2/ not changing anything.

I'm fine with both.

Let's put those two options to a vote maybe?

**Comment by stas00** [comment]
> > Ideally we can then rewrite all the existing blog posts to remove the id as well to avoid confusion for future authors which may try to copy the old setup.
> 
> As discussed before (can't find the thread right now...), we shouldn't rename the existing folders because it would break the existing assets URLs linked from the Internet

like diagrams - yes, that's a very good point. Thank you for thinking of that, Julien.

> So this leaves us with the options of 1/ ommitting the id going forward, or 2/ not changing anything.
> 
> I'm fine with both.
> 
> Let's put those two options to a vote maybe?

Sounds good to me.

**Comment by stas00** [comment]
That works, Julien.

As it doesn't look like anybody else is going to chime in, should we just update the guide to use the 3rd option instead?

**Comment by julien-c** [comment]
sounds good to me

Thanks for finding a satisfactory middleground with me :)

**Comment by stas00** [comment]
https://github.com/huggingface/blog/pull/538

**Comment by julien-c** [comment]
this has been solved
