### ISSUE TITLE
Transformer-based Encoder-Decoder Models formula issue

### ISSUE THREAD

**Issue by Qiuzhuang** [huggingface/blog#54]
![image](https://user-images.githubusercontent.com/334695/96072967-07b59e80-0ed8-11eb-91db-fc32e147f225.png)

Within this formula, 

![image](https://user-images.githubusercontent.com/334695/96073078-43506880-0ed8-11eb-8d81-9015a238d77c.png)

should we change 𝐱′1 to 𝐱′2?

Thanks.

**Comment by patrickvonplaten** [comment]
great catch! :-) Will update it

**Comment by patrickvonplaten** [comment]
should be good! Thanks a lot for the hind @Qiuzhuang !
