### ISSUE TITLE
 Types of Tasks nomenclature in the Deep RL Intro

### ISSUE THREAD

**Issue by RamAnanth** [huggingface/blog#570]
In the [Introduction to Deep Reinforcement Learning Blog](https://huggingface.co/blog/deep-rl-intro#type-of-tasks), the two types of tasks mentioned are "Episodic" and "Continuous". In order to avoid any confusion with "Continuous" referring to the nature of State/Action Space and to be consistent with the definitions according to the most commonly followed Sutton and Barto textbook, it would be great if "Continuous" is changed to "Continuing" wherever it appears with respect to the type of tasks.

**Comment by simoninithomas** [comment]
Merged it thanks again for your feedback 🤗  #573
