### ISSUE TITLE
Transformers-based Encoder-Decoder Models: `Is encoding for 'Ich' equal to its perturbed version?:  True` but in the code it's True just because they are computed exactly the same way

### ISSUE THREAD

**Issue by vgrabovets** [huggingface/blog#61]
@patrickvonplaten ,please, take a look at the code:
`decoder_output_vectors = model.base_model.decoder(decoder_input_ids, encoded_output_vectors, None, None, None, return_dict=True).last_hidden_state`

`decoder_output_vectors_perturbed = model.base_model.decoder(decoder_input_ids, encoded_output_vectors, None, None, None, return_dict=True).last_hidden_state`

You pass `decoder_input_ids` in both cases, it's exactly the same computation. If I pass `decoder_input_ids_perturbed` in the second case, then `torch.allclose(lm_logits[0, 0], lm_logits_perturbed[0, 0], atol=1e-3)` is not `True` anymore.

And do they really have to be the same? Decoder also uses cross-attention on top of unidirectional attention. And in cross-attention `ich` will have access to encoded and processed `es` or `das` and it may cause difference in the last hidden state of `ich`. Is this right?

Both `lm_logits` and `lm_logits_perturbed` predict correctly next word as Auto.

I'm really interested in your opinion.

The article itself is really great, thank you.

**Comment by patrickvonplaten** [comment]
Hey @vgrabovets - you're absolutely right! 

Not sure what I've done there. First, the input is wrong in the example and should be `decoder_input_ids_perturbed` and second, the results is obviously not the same due to the `cross_attention_layer`. => I'll update the blog post in a couple of days. Thanks very much for reporting the error!

**Comment by patrickvonplaten** [comment]
Issue should be solved with: https://github.com/huggingface/blog/commit/5913cce7a1e45ec6a3a4a45f9604e82c5d7c6f88
