### ISSUE TITLE
How can this be used with sd1.5 and other models? 

### ISSUE THREAD

**Issue by G-force78** [huggingface/blog#630]
Hi, thanks for this I had a quick go on 1.4 yesterday the speed increase is incredible, is there any way to use it with 1.5 or custom/dreambooth models? I tried substituting the models in the code but it came up with errors.

**Comment by pcuenca** [comment]
Hi @G-force78! Can you please open an issue in [the diffusers repo](https://github.com/huggingface/diffusers/issues). A reproducible example of a short code snippet that demonstrates the problem would be really helpful, as well as any error messages you got.

Thanks a lot!
