### ISSUE TITLE
How to transcribe a simple audio file with a fine-tuned Whisper model ?

### ISSUE THREAD

**Issue by juliendespres** [huggingface/blog#634]
First of all, thanks to @sanchit-gandhi for writing the tutorial https://huggingface.co/blog/fine-tune-whisper.

My question is maybe obvious, but I searched everywhere on the net without result :  how can I transcribe an audio file stored on my file system using a fine-tuned model without going through a GUI ?
My goal is to evaluate the performance of the model on our internal test data, and I do not want to upload files one by one.
Could you add a paragraph on this subject in the blog,  please ?

Thanks in advance.

**Comment by sanchit-gandhi** [comment]
Hey @juliendespres,

You can first create a custom audio dataset using your preferred method: https://huggingface.co/docs/datasets/audio_dataset#create-an-audio-dataset

This should only require 1-2 new lines of code!

You can then evaluate your fine-tuned model:
```python
from datasets import load_dataset
from transformers import WhisperForConditionalGeneration, WhisperProcessor
import torch
from evaluate import load

my_dataset = load_dataset("your-username/the-dataset-name-that-you-picked", split="test")

processor = WhisperProcessor.from_pretrained("your-username/the-model-name-that-you-picked")
model = WhisperForConditionalGeneration.from_pretrained("your-username/the-model-name-that-you-picked")
model.to("cuda")

def map_to_pred(batch):
    audio = batch["audio"]
    input_features = processor(audio["array"], sampling_rate=audio["sampling_rate"], return_tensors="pt").input_features

    with torch.no_grad():
        predicted_ids = model.generate(input_features.to("cuda"))

    batch["prediction"] = processor.batch_decode(predicted_ids, normalize = True)[0]
    return batch

result = my_dataset.map(map_to_pred)

wer = load("wer")
print(100 * wer.compute(references=result["text"], predictions=result["prediction"]))
```

This will evaluate on a sample-by-sample basis (batch size of 1).

If you want to do batched inference, you can follow the code exactly as presented in the blog. Simply set `do_train=False` in the training arguments to just run evaluation.

The forum is an excellent place to ask such questions: https://discuss.huggingface.co

**Comment by juliendespres** [comment]
Thanks a lot!
I'm going to try this.

**Comment by sanchit-gandhi** [comment]
Sure no worries! If you have any further issues don't hesitate to post on the forum and tag me 🤗 Good luck with your evaluation!

**Comment by sanchit-gandhi** [comment]
Hey @juliendespres - did this work?

**Comment by juliendespres** [comment]
Hi @sanchit-gandhi,
Not really, there is still some problems I did not resolved.
I'm not a Python expert so I do not progress quickly.

First of all, it seems that the function  "trainer.push_to_hub(**kwargs)" do not push everything needed to run the model because I obtained the following error when I try to use it :
processor = WhisperProcessor.from_pretrained("JulienDespres/whisper-small-fr")
OSError: Can't load tokenizer for 'JulienDespres/whisper-small-fr'. (...) make sure 'JulienDespres/whisper-small-fr' is the correct path to a directory containing all relevant files for a WhisperTokenizer tokenizer.

To overcome the problem I use the model trained by Yocel1 : "Yocel1/whisper-small-fr".
I managed to load my own data with
audio_dataset = Dataset.from_dict({"audio": ["my_audio"]}).cast_column("audio", Audio())
and to decode with your function "map_to_pred", but it seems to decode only the first 30s.

I am still trying to solve the problems, thanks again for your help.

**Comment by sanchit-gandhi** [comment]
Hey @juliendespres! Sorry that was a bug with the training script - it's fixed in the colab now so that everything should be pushed to Hub. Before, only the feature extractor was being pushed to hub, but the tokenizer missing.

However, since we don't train any aspect of the processor (feature extractor + tokenizer), we can just load this from the original checkpoint:

```python
from datasets import load_dataset
from transformers import WhisperForConditionalGeneration, WhisperProcessor
import torch
from evaluate import load

my_dataset = load_dataset("your-username/the-dataset-name-that-you-picked", split="test")

processor = WhisperProcessor.from_pretrained("openai/whisper-small")  # we can just load the 'official' processor
model = WhisperForConditionalGeneration.from_pretrained("JulienDespres/whisper-small-fr")  # and use your trained weights!
model.to("cuda")

def map_to_pred(batch):
    audio = batch["audio"]
    input_features = processor(audio["array"], sampling_rate=audio["sampling_rate"], return_tensors="pt").input_features

    with torch.no_grad():
        predicted_ids = model.generate(input_features.to("cuda"))

    batch["prediction"] = processor.batch_decode(predicted_ids)[0]
    return batch

result = my_dataset.map(map_to_pred)

wer = load("wer")
print(100 * wer.compute(references=result["text"], predictions=result["prediction"]))
```

This is a limitation of the Whisper model - it can only transcribe 30s audio chunks at a time (see https://huggingface.co/blog/fine-tune-whisper#load-whisperfeatureextractor)

We're currently working on adding functionality for long-form transcription (audio samples > 30s)!
