### ISSUE TITLE
Dereference blog post

### ISSUE THREAD

**Issue by fxmarty** [huggingface/blog#675]
I think it would be meaningful to dereference: https://huggingface.co/blog/infinity-cpu-performance

I think Infinity is a defunct product, and it is still showing very top for some significant search queries on Google:
* `transformers deployment intel cpu`
* `transformers inference latency`
* `hugging face transformers inference latency`
* `transformers deployment cpu`

even showing first compared to other current solution (e.g. Optimum-intel).

Not quite sure how to do it.

cc @osanseviero @mfuntowicz @philschmid

**Comment by philschmid** [comment]
cc @jeffboudier

**Comment by fxmarty** [comment]
Infinity is not really part of Optimum package, is it?

If we want to keep the blog, I think a refactor could be good with a section at the top redirecting towards Optimum, while keeping the rest and making clear it is defunct / not open source. What do you think?

**Comment by jeffboudier** [comment]
Yes I think we should keep and update the blog post with an Update section at the top about:
- Inference Endpoints as our new inference solution - Infinity is not available anymore
- Optimum-Intel to accelerate your models on CPU
- Our team can accelerate your models -> EAP

**Comment by julien-c** [comment]
this can be closed
