### ISSUE TITLE
RuntimeError: Input type (float) and bias type (c10::Half) should be the same

### ISSUE THREAD

**Issue by tralala87** [huggingface/blog#899]
While running "Zero-shot image-to-text generation with BLIP-2" I get the following error:
`RuntimeError                              Traceback (most recent call last)
[<ipython-input-14-e7a5a0c17cca>](https://localhost:8080/#) in <module>
      1 inputs = processor(image, return_tensors="pt")
      2 
----> 3 generated_ids = model.generate(**inputs, max_new_tokens=20)
      4 generated_ids = generated_ids.to(device)
      5 generated_text = processor.batch_decode(generated_ids, skip_special_tokens=True)[0].strip()

8 frames
[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    457                             weight, bias, self.stride,
    458                             _pair(0), self.dilation, self.groups)
--> 459         return F.conv2d(input, weight, bias, self.stride,
    460                         self.padding, self.dilation, self.groups)
    461 

RuntimeError: Input type (float) and bias type (c10::Half) should be the same`

**Comment by MaazBinMusa** [comment]
This exact line and code is giving me the following error.

RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'
