### ISSUE TITLE
Type in collab file

### ISSUE THREAD

**Issue by Haard-Shah** [huggingface/blog#901]
For the "Extra: How to fine-tune a Sentence Transformer model" all the code references are of xxxx**B** styled variables to apply the same procedure to the Sentence BERT model. However, when the model training is performed using mode.fit() the .fit() method is called upon the incorrect model. It should be modelB.fit(....) instead of model.fit() as the model references a variable for above section which was not intended to be used here. 

Here is updated piece of code if you need: 
`modelB.fit(train_objectives=[(train_dataloaderB, train_lossB)],
          epochs=num_epochsB,
          warmup_steps=warmup_stepsB) `

**Comment by osanseviero** [comment]
Fixed in https://github.com/huggingface/blog/pull/902
