### ISSUE TITLE
About <mask> tokens while training model

### ISSUE THREAD

**Issue by ithieund** [huggingface/blog#91]
Hi @julien-c ,
BERT is a mask language model which will mask the tokens at about 15% while training to train model how to predict the masked tokens, right?

But in the tutorial 'How to train a new language model from scratch using Transformers and Tokenizers', I don't see anywhere to put the <mask> token for training, or at least specify the rate of <mask> tokens if the model already do that inside
https://github.com/huggingface/blog/blob/master/how-to-train.md

Can you help me to point this out?
Thank you very much!

**Comment by julien-c** [comment]
If you look at the Colab notebook linked from the blogpost, you'll see those lines:

```
from transformers import DataCollatorForLanguageModeling

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, mlm=True, mlm_probability=0.15
)
```

There you can tweak the `mlm_probability`.

Hope this helps, and feel free to ask on the forum instead.

**Comment by ithieund** [comment]
@julien-c thank you very much :)
