### ISSUE TITLE
update blog/fine-tune-segformer.md code and inference example

### ISSUE THREAD

**Issue by turcuciprian** [huggingface/blog#914]
### A few issues:
1. label2id variable starts a { but does not close it.
2. reduce_labels=feature_extractor.reduce_labels,
problem is feature_extractor.reduce_labels does not exist, unless you remove the s at the end... it's feature_extractor.reduce_label

### A suggestion:
At the end of the inference part, to write an example on how to run a image file trough the model and how it can be outputed as a image with the mask applied... or just as a mask (example with code and if it makes sense, explained just like the rest of the article)

**Comment by segments-tobias** [comment]
I'll have a look at this in the coming week!

**Comment by turcuciprian** [comment]
Hey, how's the update going?
I managed to train a similar model with Fast.ai and, since I have no urgent use for "the fix" on this model, I am curious to compare it to the fast.ai model performance in speed and results.
Just checking in, cheers!

**Comment by segments-tobias** [comment]
@turcuciprian Didn't get to it yet last week, and I'm on holiday this week, so expect the solution next week.
In the meantime, could you clarify your suggestion about inference please? The colab already contains inference code and code to create an output image with the mask.

**Comment by turcuciprian** [comment]
Hi @segments-tobias ,
if the colab already includes inference code, it is unclear how exactly that can be used and how one can add a untrained image to it so that it outputs the mask for it.
