### ISSUE TITLE
Question: need help 

### ISSUE THREAD

**Issue by qlinsey** [huggingface/blog#975]
Hi, Thanks for the blog (https://huggingface.co/blog/dreambooth). 
I have one question need your help. I used dreambooth similar as what you described here. After training, the generated images look fine. As my understanding, it  can say the reconstructed images are good after training. But once I create text context prompt (similar as Dream Booth paper describe in appendix Figure 10:  TOKEN on the beach/in the snow etc) . The appearance of generated image changed include color and pattern , similar as Failure case described in Figure 9(b).  Do you have this experience, can please provide some suggestions? My task is to generate similar images as initial images and put them to different back-gounds/contexts with minimum changing of initial images. 

Look forward to hearing from you soon, please help on this question! I have tried so many times. Thank you!

**Comment by qlinsey** [comment]
Can anyone help to reply? thanks

**Comment by osanseviero** [comment]
Hey there! This might be a question better suited for our [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63) or our [Discord server](http://hf.co/join/discord). :hugs: would you mind reposting your question over the forum please?

**Comment by qlinsey** [comment]
Thanks, i posted to forum: https://discuss.huggingface.co/t/entanglement-issue-of-dreambooth-images/35229
